### PR TITLE
Sign Up Page

### PR DESCRIPTION
**Pull request by poojasable28**
Attached the updated **Sign Up Page**. Let me know your reviews.

### CODE REVIEW

**Comment by utkarsh-patil** [comment]
Have you created new branch for it ?

**Review by madhutiwatne — COMMENTED** [review]
format is good bt change background

**Comment by poojasable28** [comment]
Yes Utkarsh, I have created a new branch, viz., Sign-Up as you had mentioned today.

**Comment by utkarsh-patil** [comment]
Awesome. Will check it tomorrow. Thanks 
Dhiraj will merge it after the review

**Comment by utkarsh-patil** [comment]
Will check n let you know.

**Comment by poojasable28** [comment]
Sure. Let me know if the code doesn't work.

**Comment by utkarsh-patil** [comment]
Pooja can you tell what changes are added in this version ?

**Comment by poojasable28** [comment]
Yes, actually I have changed the code totally. In the previous sign-up.html file I had used <table> tag and in the updated one I have done the positioning of elements through the sign-up.css file. Also I have added the sign-up.js file here, but the code doesn't seem to work with it. So I have attached the JS file for reference.

**Pull request merged**
