### PR TITLE
Merge pull request #9 from utkarsh-patil/dev-team

### PR DESCRIPTION
**Pull request by madhutiwatne**
give review

### CODE REVIEW

**Comment by madhutiwatne** [comment]
demo

**Comment by utkarsh-patil** [comment]
Why label is duplicate added here ?

**Comment by dhiraj336** [comment]
It's an demo pull request.

**Comment by madhutiwatne** [comment]
its just for demo

**Comment by utkarsh-patil** [comment]
Ok. Cool. I was concerned about the label you choose as duplicate i instead of issue or enhancement

**Comment by madhutiwatne** [comment]
actually i did it just for demo thats why i choose dupliucate if there is any issue occure ill choose another

**Comment by utkarsh-patil** [comment]
Oh I see ☺

**Pull request merged**
