### PR TITLE
about us

### PR DESCRIPTION
**Pull request by madhutiwatne**

### CODE REVIEW

**Comment by utkarsh-patil** [comment]
I will check it n let you know

**Comment by poojasable28** [comment]
Checked out the files. All cool. Just try changing the **colors** and modify the **alignments of text**. And also when you give the path **keep the src or href value short** for any field, don't put the value right from your disk name. Do commit the images used in the view files.
Thanks.

**Comment by utkarsh-patil** [comment]
Keep images inside images folder which is in webapp folder. Also don't mention actual path of image do u relative path for images.

**Comment by utkarsh-patil** [comment]
Also accommodate changes suggested by Pooja

**Review by dhiraj336 — APPROVED** [review]

**Pull request merged**
